### ISSUE TITLE
sidebar-card.js:192:2849 SyntaxError: invalid regular expression flag s

### ISSUE THREAD

**Issue by hiddevanbrussel** [DBuit/sidebar-card#1]
I have problems with the sidebar-card. In the logging i get the following error. 

on line 192 character 2849 is see this. I'am not good with coding but is this a problem?
/<li>(.*?)<\/li>/gs)

**Comment by DBuit** [comment]
Hi that is strange. I have no errors if the coding was wrong everyone should have the error i expect. Are you using the `template` part in your configuration? and can you share it?

**Comment by hiddevanbrussel** [comment]
The problem is solved. After a restart of Home-Assistant its gone
