### ISSUE TITLE
Current version reports as 0.1.8.4

### ISSUE THREAD

**Issue by ccMatrix** [DBuit/sidebar-card#102]
In the browsers developer console the latest dist file reports the wrong version:

![image](https://github.com/DBuit/sidebar-card/assets/96917/51e96970-77db-4c5d-a53a-f7f8826e1723)

It looks like the constant `SIDEBAR_CARD_VERSION` in the js file is not changed on new releases.
![image](https://github.com/DBuit/sidebar-card/assets/96917/82e790c0-2310-4b93-8243-cbfee0583a09)

**Comment by DBuit** [comment]
thanks for mentioning i forget it a few times is see ;)
