### ISSUE TITLE
Scrollbar added to sidebar after latest update 1.9.5

### ISSUE THREAD

**Issue by marxdrive** [DBuit/sidebar-card#103]
![scrollbar](https://github.com/DBuit/sidebar-card/assets/35245949/771867aa-73b7-48c3-9c76-1ad704323d28)

Is it possible to remove the scrollbar? It never appeared prior to the latest update - It's been installed for a few months.

**Comment by BlueSnake830** [comment]
It was integrated with 1.9.5. 
I only see a horizontal scroll bar. I assume your vertical bar appears, because the sidebar is "higher than the screen resoluation".
For my horizontal bar, I tried different width percentage (10 - 25) without being able to remove it.

![image](https://github.com/DBuit/sidebar-card/assets/75618694/e4caabe4-9c29-484f-a4a8-a77cf48f49e9)

**Comment by DBuit** [comment]
The vertical is true, horizontal should not be there. Will check it out

**Comment by marxdrive** [comment]
I solved the Vertical scrollbar by lowering the clock padding:

    .digitalClock {
      padding-top: 20px;
}

I have widened the sidebar in desktop by using:

  width:
    desktop: 16
    mobile: 0
    tablet: 22

The scrollbar remains despite being wide enough. I look forward to the fix.

**Comment by pressurejets** [comment]
Same problem. got both hoz and vert scroller, i have removed all from sidecard and its still there, look forward to fix.

**Comment by marxdrive** [comment]
> Same problem. got both hoz and vert scroller, i have removed all from sidecard and its still there, look forward to fix.

@pressurejets The fix will only be for the horozontal scrollbar, you will have to change the dimensions of your sidebar to fix the vertical scrollbar. Lowering the padding at the top of my clock from 70px to 20px worked for me:

.digitalClock {
  padding-top: 20px;

**Comment by pressurejets** [comment]
normal 
`.sidebar-inner
    {
      overflow: hidden;
     
      }`

would remove both x,y scrollbar but uts not happening lol, just have to wait for fix

**Comment by DBuit** [comment]
You can try adding !important to overwrite te mistake i wil try to make an fix monday

**Comment by pressurejets** [comment]
` .sidebar-inner
    {
      overflow-x: hidden !important;`

worked a charm thank you, Dbuit and great sidebar

**Comment by DBuit** [comment]
Issue should be fix in new release
