### ISSUE TITLE
Bottom custom card is not displayed after reloading

### ISSUE THREAD

**Issue by Franzi24** [DBuit/sidebar-card#119]
Unfortunately, I have always had the problem that the bottom section of my sidebar is not displayed when the dashboard is reloaded. Only when I click on a specific dashboard of my own and then back again does the content appear. I have to make these clicks every day so that my dashboard is displayed in full. This phenomenon is extremely annoying in the long run and I keep trying to find the cause, but to no avail. However, this log entry can be found. Can you perhaps help with the log? In any case, I am sure that it has nothing to do with my content/code on the sidebars, as this problem also exists if I only use the sample content from the documentation.

Logger: frontend.js.modern.202408090
Quelle: components/system_log/__init__.py:333
Erstmals aufgetreten: 10:06:33 (254 Vorkommnisse)
Zuletzt protokolliert: 14:49:23

Uncaught error from Chrome 127.0.0.0 on Windows 10 TypeError: cardElement.setConfig is not a function /hacsfiles/sidebar-card/sidebar-card.js:18113:33
Uncaught error from Chrome 127.0.0.0 on Windows 10 TypeError: Cannot convert undefined or null to object getOwnPropertyNames (node_modules/deep-freeze/index.js:4:9) _handleConfigChanged (src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts:330:34) call (src/lit-html.ts:2018:28) dispatchEvent (src/common/dom/fire_event.ts:76:7) this._updateConfigElement (src/panels/lovelace/editor/hui-element-editor.ts:140:16)
Uncaught error from Chrome 127.0.0.0 on Windows 10 TypeError: Cannot read properties of null (reading 'shadowRoot') getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23) SidebarCard.updateSidebarSize (/hacsfiles/sidebar-card/sidebar-card.js:18050:30) /hacsfiles/sidebar-card/sidebar-card.js:18088:18
Uncaught error from Chrome 127.0.0.0 on Windows 10 TypeError: Cannot read properties of null (reading 'shadowRoot') getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23) createCSS (/hacsfiles/sidebar-card/sidebar-card.js:18418:26) updateStyling (/hacsfiles/sidebar-card/sidebar-card.js:18692:66) /hacsfiles/sidebar-card/sidebar-card.js:18876:17
Uncaught error from Chrome WebView 127.0.6533.103 on Android 14 TypeError: cardElement.setConfig is not a function /hacsfiles/sidebar-card/sidebar-card.js:18113:33

**Comment by joelis10** [comment]
this is an issue for me too and particularly annoying since I cast my dashboard to my Nest Hub Max and there's no way to force a reload on there
