### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by stibe881** [DBuit/sidebar-card#13]
Is there a way to make the background transparent?

**Comment by timota** [comment]
i did this in style and it works
```
--sidebar-background: transparent!important;
```

**Comment by stibe881** [comment]
@timota 
I tried. But this doesnt work..:
![7C7D16D0-8FEB-415F-A2AA-3D4C682FFD1B](https://user-images.githubusercontent.com/24219649/83801173-f9917f00-a6a8-11ea-8954-c7b5caf3a91e.png)

**Comment by DBuit** [comment]
@stibe881 if you have a background under your other cards than this won't be visible under the sidebar so i think that this is what you want or not? because it you make it transparent it will probably just be white always

**Comment by timota** [comment]
it will be a good idea to add an option to set an image as a  background. Can you implement it please ?

**Comment by cismarine** [comment]
background transparency level would be perfect as well as option to use image.
Otherwise it is very useful UI enhancement.
Thanks!
