### ISSUE TITLE
Does not work with multiple dashboards

### ISSUE THREAD

**Issue by dolphin8111** [DBuit/sidebar-card#14]
This is a great card that does exactly what I need. However I found out that it works only for a single dashboard.

I have multiple dashboards to better organize my views. There would be too many tabs for a single one. I.e. I used a dashboard for overviews and then a separate dashboard for each of the two floors of our house.

Installation details:
- arch: armv7
- channel: stable
- docker: 19.03.8
- hassos: "4.10"
- homeassistant: 0.111.4
- logging: info
- machine: raspberrypi4
- supervisor: "227"
- supported_arch:
- - armv7
- - armhf

There are three dashboards and I copy-pasted the exact same configuration for sidebar-card at the beginning of each yaml using the raw configuration editor.

Observed behaviour:
- When I open a dashboard (say 'A'), the sidebar does not appear
- When I refresh the browser, the sidebar appears and works perfectly
- When I select any tab on dasboard A, the sidebar stays on and behaves properly
- If I select another dashboard (say 'B'), the sidebar disappears.
- If I now get back to dashboard A, the sidebar appears again and works properly, as before
- Back to dashboard B, the sidebar disappears again
- If I refresh the browser on dashboard B, I have now have a properly working sidebar for dashboard B
- Back to dashboard A, the sidebar is not there no more

In fact, it looks like the sidebar 'sticks' only to the dashboard, where the browser was last refreshed. I also tried to clear browser cache, but that doesn't change anything.

It would be great, if that could be fixed. Thanks for your help.

**Comment by maxgyver87** [comment]
I have the same problem.
would be interesting to know I anyone has the sidebar visible 
on anything other than /lovelace to know if it is a card or a setup problem.

Really like this card so far

**Comment by kenstone** [comment]
I have the same problem. This card is awesome looking, but I have a separate dashboard that's only visible on my kitchen tablet. That's the only dashboard I want this sidebar card on.

**Comment by madansu** [comment]
It would be great if this worked on multiple dashboards. 
I have a temporary dashboard that I would like to build completely, before switching to this new dashboard setup.
