### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null Home Assistant já iniciou

### ISSUE THREAD

**Issue by gamer06** [DBuit/sidebar-card#18]
Hi.
Everytime i have this error. I dont know why because i think its working fine. What can i do to eliminate de error?
https://gyazo.com/48d2a3b3e8b17d4931d959562f83532c

Thanks

**Comment by gamer06** [comment]
Any solution for that issue?

`https://*****.duckdns.org:8123/hacsfiles/sidebar-card/sidebar-card.js:17843:38 TypeError: null is not an object (evaluating 'this.bottomCard.type')
https://***.***.**.80:8123/hacsfiles/sidebar-card/sidebar-card.js:17843:39 Uncaught TypeError: Cannot read property 'type' of null`

**Comment by wtrbuit** [comment]
Hi, can you make sure you have the latest release and see if the issue still occurs?
