### ISSUE TITLE
Sidebar doesn't work in Firefox

### ISSUE THREAD

**Issue by hiddevanbrussel** [DBuit/sidebar-card#2]
The sidebar doesn't work in Firefox

SyntaxError: invalid regular expression flag ssidebar-card.js:195:2997

![afbeelding](https://user-images.githubusercontent.com/54264973/75768277-52691880-5d44-11ea-9c30-d88adc79b57b.png)

**Comment by blake-sherrill** [comment]
Same here.

**Comment by DBuit** [comment]
Hi @hiddevanbrussel and @blake-sherrill,

just released V0.1.2 with a fix for firefox
