### ISSUE TITLE
hide top menu ( custom header not available)

### ISSUE THREAD

**Issue by syedkami** [DBuit/sidebar-card#21]
hi,

hide top menu is not working due to custom header no longer available.
digital clock is half inside of top header, mean top header is half covered digital clock or first element of side bar.

**Comment by CM000n** [comment]
I'll go along with that. I have exactly the same problem at the moment.

**Comment by sundancekid80** [comment]
Same for me!

**Comment by moh-Brent** [comment]
yup same here, really liking this though

**Comment by michaelstein60** [comment]
Add me to the list. Loving this sidebar but really need top menu gone to complete the look.

Thanks for the good work.

**Comment by BigProgrammer2000** [comment]
For a quick fix you have to open the "sidebar-card.js" with an editor and search for "ch-header". There should be 3 entries. You then have to replace the 3 entries with "app-header", then it will work again.

**Comment by moh-Brent** [comment]
I tried that and the sidebar stopped working

**Comment by h4nnes** [comment]
same here... after setting hideTopMenu to true (and replacing ch-header with app-header) the sidebar is gone... Any soluiton?

**Comment by BigProgrammer2000** [comment]
The new version 0.1.7.9 still did not fix the problem.
My fix for this post refers to the side-bar version 0.1.7.9 and home assistant version 2021.3.0 and newer with lovelace-ui.

4 entries in this version

17961       `const header = root.shadowRoot.querySelector('ch-header');` 
to
17961       `const header = root.shadowRoot.querySelector('app-header');`

18472       `const header = root.shadowRoot.querySelector('ch-header');`
to
18472       `const header = root.shadowRoot.querySelector('app-header');`

18561       `if (root.shadowRoot.querySelector('ch-header'))`
18562           `root.shadowRoot.querySelector('ch-header').style.display = 'none';`
to
18561       `if (root.shadowRoot.querySelector('app-header'))`
18562           `root.shadowRoot.querySelector('app-header').style.display = 'none';`

**Comment by shadowdro** [comment]
I am seeing the same issue. 

sidebar:
  hideTopMenu: true
  hideHassSidebar: true
