### ISSUE TITLE
Icon is not a clickable element

### ISSUE THREAD

**Issue by peteywhit** [DBuit/sidebar-card#24]
I started messing around creating a sidebar menu with no text and icons only.
I was using CSS styles to make everything work and align properly, when I noticed that the icon that is shown will not let you navigate. 

This makes it harder for the SO, kids, or visitors to navigate when they aren't aware that you have to click in dead space next to the icon.

I was able to get around this by adding the same `data-type`, `data-path`, and `data-menuitem` for the `${sidebarMenuItem.icon}`.

Once copied from the `li` element, I can now navigate the menu without issue no matter where I touch.

```
        ${sidebarMenu && sidebarMenu.length > 0 ? html `
        <ul class="sidebarMenu">
          ${sidebarMenu.map(sidebarMenuItem => {
            return html `<li @click="${e => this._menuAction(e)}" class="${sidebarMenuItem.state && this.hass.states[sidebarMenuItem.state].state != 'off' && this.hass.states[sidebarMenuItem.state].state != 'unavailable' ? 'active' : ''}" data-type="${sidebarMenuItem.action}" data-path="${sidebarMenuItem.navigation_path ? sidebarMenuItem.navigation_path : ''}" data-menuitem="${JSON.stringify(sidebarMenuItem)}">
              ${sidebarMenuItem.name}
              ${sidebarMenuItem.icon ? html `<ha-icon @click="${e => this._menuAction(e)}" data-type="${sidebarMenuItem.action}" data-path="${sidebarMenuItem.navigation_path ? sidebarMenuItem.navigation_path : ''}" data-menuitem="${JSON.stringify(sidebarMenuItem)}" icon="${sidebarMenuItem.icon}" />` : html ``}
            </li>`;
        })}
        </ul>
        ` : html ``}
```

![image](https://user-images.githubusercontent.com/67245120/104860429-31280100-58f1-11eb-8947-b6907a12096e.png)

I'm creating an issue instead of a pull request, because I'm not sure if this is the correct way to do this or if there is a better way.

**Comment by CptRic** [comment]
> 
> 
> I started messing around creating a sidebar menu with no text and icons only.
> I was using CSS styles to make everything work and align properly, when I noticed that the icon that is shown will not let you navigate.
> 
> This makes it harder for the SO, kids, or visitors to navigate when they aren't aware that you have to click in dead space next to the icon.
> 

Is it possible to share your CSS style? I'm trying to achieve something similar only with icons like you, but i don't know how to start properly
Looks awesome btw.

**Comment by peteywhit** [comment]
> Is it possible to share your CSS style? I'm trying to achieve something similar only with icons like you, but i don't know how to start properly
> Looks awesome btw.

Sorry for the late reply, but I've stepped away from my projects for a while.
I've changed the look a little bit since, but my dashboard still isn't up and running by any means, but here is the styles and an image of what it looks like now.

![image](https://user-images.githubusercontent.com/67245120/118421641-14c18880-b687-11eb-857a-b7472cb7ddbb.png)

`  style: |
    :host {
      background-color: var(--sidebar-background-color) !important;
    }
    h1.digitalClock {
      font-size: 2.57em !important;
      font-weight: 300 !important;
      text-align: center;
      line-height: 30px !important;
      width: inherit;
      margin-left:-20px;
    }
    h1 {
      margin-bottom: 0px !important;
      color: var(--primary-text-color) !important;
    }
    h2 {
      line-height: 1.2em !important;
      width: inherit;
      margin-left: -20px !important;
      color: var(--primary-text-color) !important;
    }
    .date {
      text-align: center;
      font-size: 1.2em !important;
    }
    .sidebarMenu {
      margin: -20px 0px 0px 0px !important;
      padding: 20px 0px !important;
      border-top: none !important;
      border-bottom: none !important;
    }
    .sidebarMenu li {
      font-size: 14px !important;
      color: var(--text-primary-color) !important;
      -webkit-tap-highlight-color: transparent;
      padding: 10px 15px !important;
      text-align: center !important;
      margin: 10px 0px;
    }
    .sidebarMenu li ha-icon{
      float: none !important;
      color: var(--sidebar-icon-color) !important;
    }
    .sidebarMenu li.active {
      background-color: rgba(0,0,0,0) !important;
      color: var(--primary-text-color) !important;
      border-radius: 0px !important;
      border-right: 3px solid var(--primary-color) !important;
      width: 100% !important;
      margin-left: -13px;
    }
    .sidebarMenu li.active ha-icon {
      color: var(--sidebar-selected-icon-color) !important;
      margin-left: -4px !important;
    }`
