### ISSUE TITLE
Failed to load resource: http://homeassistant.local:8123/hacsfiles/sidebar-card/index.m.js.map

### ISSUE THREAD

**Issue by CedricRBR** [DBuit/sidebar-card#25]
## Issue

My sidebar isn't loading because the server doesn't find the following file: 

`/hacsfiles/sidebar-card/index.m.js.map`

## General infos
 - Version: 0.1.7.7
 - Installed via HACS

**Comment by oziee** [comment]
that error about can't find the .map has nothing to do with it.. that error only shows when using the developer tools window
ie https://theme.co/forum/t/failed-to-load-resource-js-map/43504

make sure there is no error referencing just the js file
make sure the file is in the folder
make sure you restart the server t one sure its loading in the resources
