### ISSUE TITLE
Not Working on Fully Kiosk Browser Fire HD 8 

### ISSUE THREAD

**Issue by mcgeebc** [DBuit/sidebar-card#32]
I have the sidebar card working great on Chrome, but it won't work on my Fire HD 8 using Fully Kiosk Browser. I have read that it's likely due to the Fire Tablet running a lower version of Webview. It seems that can't be upgraded. Other custom cards also struggle with older versions of Webview. 

I had the same issue with the 'kiosk' card, but found a workaround to define the 'type' as 'js' instead of 'module'. That same workaround didn't work for sidebar-card.

Are there any workaround for this card? Has anyone managed to make this work running fully-kiosk on a Fire Tablet?

**Comment by jcgonzalezdelgado** [comment]
I have a Fire HD 8 Plus and it's working fine. You just need to side-load a few things :)

**Comment by mcgeebc** [comment]
> I have a Fire HD 8 Plus and it's working fine. You just need to side-load a few things :)

What did you need to side load?

**Comment by jcgonzalezdelgado** [comment]
> > I have a Fire HD 8 Plus and it's working fine. You just need to side-load a few things :)
> 
> What did you need to side load?

Just look for Fire Toolbox V15.0, in XDA Developers. You can remove a lot of stuff and also install Google needed things, like Chrome and so.

**Comment by wtrbuit** [comment]
I am closing this issue since it is not related to the development of the module.
