### ISSUE TITLE
Background color not working after update to 0.1.8.0

### ISSUE THREAD

**Issue by MantasIgnatjevas** [DBuit/sidebar-card#38]
`  style: |
    :host {
        --sidebar-text-color: #000;
        --sidebar-background: #1d2427;
        }`
After the update to 0.1.8.0, the sidebar background reverted to the original color (white), and it does not react to --sidebar-background command anymore. The text color works fine, I can change it to whatever I want.

**Comment by jamesahendry** [comment]
Same issue with me
