### ISSUE TITLE
showTopMenuOnMobile doesn't work anymore

### ISSUE THREAD

**Issue by bckthomas** [DBuit/sidebar-card#44]
Hi
Since last update, the top menu doesn't display on mobile.
The option showTopMenuOnMobile is set to true

Thanks

**Comment by asifma** [comment]
Same problem here...

**Comment by anhnvme** [comment]
Same problem here...

**Comment by wtrbuit** [comment]
Sorry to keep you guys waiting so long. I fixed the issue and will come with the next release.
