### ISSUE TITLE
Is it possible to remove these 2 lines?

### ISSUE THREAD

**Issue by Boogaard53** [DBuit/sidebar-card#48]
![photofunny net_](https://user-images.githubusercontent.com/87951112/147112172-12b17d62-3afd-492e-bd4b-baf3c1ce3da4.jpg)

**Comment by ry8s** [comment]
You should be able to add the following to your sidebar config:

sidebar:
  style: |
    .sidebarMenu {
        border-top: hidden !important;
        border-bottom: hidden !important;
    }

**Comment by Boogaard53** [comment]
Wow great thanks!

This should definitely be added to the readme.txt or did I just miss it?

**Comment by ry8s** [comment]
> 

This specific example isn't, I could see that being a useful one to point out, but with the style tag, you can change a lot of things, and it would be impossible to list it all out and maintain that.
