### ISSUE TITLE
Request: Hide Top / Hass Menu only on tablet / mobile

### ISSUE THREAD

**Issue by ry8s** [DBuit/sidebar-card#49]
I would like to hide the Top / Hass menu on my tablet display, but not my desktop so I can still easily edit and access everything else.

**Comment by DBuit** [comment]
Hi @ry8s,

I will check what i can do for now don't now if you are awere but if you add `?sidebarOff` at the end of the url when visiting your hass in browser it will disable the hide hass menu actions, just for that time.

**Comment by ry8s** [comment]
oops I missed that part in the readme, that will work just fine - thank you!

**Comment by ry8s** [comment]
Actually, still related to this, with the following settings, I'm unable to access the hass sidebar on mobile (of course), but I do handle management through my phone a bit, would it be possible for the 'showTopMenuOnMobile' property to still allow access to the hass sidebar if clicking on the top left hamburger menu?

  hideTopMenu: true
  showTopMenuOnMobile: true
  hideHassSidebar: true
