### ISSUE TITLE
What CSS style should i change to get rid of the blue select circle around the active page (room in this case)

### ISSUE THREAD

**Issue by Boogaard53** [DBuit/sidebar-card#55]
![Tablet-Home-Assistant (2)](https://user-images.githubusercontent.com/87951112/150895239-b76e67e7-0f41-47fd-9fc1-b288d8d50532.png)

**Comment by jwaz73** [comment]
In case you haven't found an answer to your question yet, this style item is in the `.sidebarMenu li.active::before` element.  By default it will take the color defined in `--sidebar-selected-icon-color`.  The default for this element is `background-color: var(--sidebar-selected-icon-color)`.  You can set this color in your style settings or can override the setting as transparent to disable the highlighting all together.
```
style: |
...
  .sidebarMenu li.active::before {
    background-color: transparent!important;
  }
...
```

That's how I solved it anyway...
