### ISSUE TITLE
hideTopMenu: true

### ISSUE THREAD

**Issue by micheleformia** [DBuit/sidebar-card#56]
Hi everyone, I have problems, I set "hideTopMenu: true", obviously I don't see the top bar anymore but I can't edit the lovelace.yaml file anymore. How can I do? I tried looking in the HA directories but nothing. Thank you all

**Comment by jtilma1** [comment]
I am having this EXACT same problem. :)

**Comment by cismarine** [comment]
> I did, however, see a workaround recommended by DBuit over in this other issue #49
> 
> If you add `?sidebarOff` to the end of the URL it will turn it off just for that session, however, if you also add it to a URL where you've disabled the sidebar and top menu it will actually turn it back on.

That's good to know. Thanks!

**Comment by fenty17** [comment]
You can also just add ?edit=1 to the end of the url which takes you straight to the edit page for that lovelace view. Not tested this with sidebar-card but currently have a kiosk mode addon and use this method to edit my wall tablet dashboard.
