### ISSUE TITLE
2 Error Messages in LOG

### ISSUE THREAD

**Issue by tonizabel** [DBuit/sidebar-card#57]
https://*******.ui.nabu.casa/hacsfiles/sidebar-card/sidebar-card.js?hacstag=2418255740184:412:9138 TypeError: null is not an object (evaluating 's.shadowRoot')

https://*******.ui.nabu.casa/hacsfiles/sidebar-card/sidebar-card.js?hacstag=2418255740184:462:18967 TypeError: a.setConfig is not a function. (In 'a.setConfig(e)', 'a.setConfig' is undefined)

Is this my mistake?

**Comment by Gilles-Clemenceau** [comment]
Same as #45
