### ISSUE TITLE
Sidebar auto hide.

### ISSUE THREAD

**Issue by cismarine** [DBuit/sidebar-card#59]
Hi,
It is not an issue, but could be useful...
When I design UI's for home automation systems and sidebar is used, than I include an option to auto hide it.
for example you select your media browser from sidebar, than after set amount of time it will slide out of view shifting main page to the left.
I would love to see it here.

**Comment by RefineryX** [comment]
+1 - would love to see this feature too.

**Comment by almighty059** [comment]
@cismarine just curious if you run or would run into resizing issues.? I've tried myself to use `px` and `%` and the `custom:stack-in-card` and it's kind of a hit-or-miss depending on how extreme the setup is for a view.

**Comment by cismarine** [comment]
yes, it is a bit like that. takes quite a while to adjust everything correctly

**Comment by RefineryX** [comment]
Hi @DBuit  - I see this has been marked as completed. How do I integrate?
