### ISSUE TITLE
with: 0 in mobile doesnt work

### ISSUE THREAD

**Issue by gamer06** [DBuit/sidebar-card#6]
Hi.  
There is a bug in the width: 0 mobile.
I still see the sidebar in the back and I shouldn't have.
Is there a solution for this?

my config:
 width:
    desktop: 25
    mobile: 0

And the screenshot:
![Screenshot_2020-03-19-20-49-18](https://user-images.githubusercontent.com/23462360/77114152-f1b82c00-6a23-11ea-8923-6859caf91479.png)

**Comment by MrHarcombe** [comment]
Not just you, having similar issue on mobile view:

![image](https://user-images.githubusercontent.com/2182915/79075259-a7a42c80-7ce9-11ea-938f-f600745848ac.png)

Any ideas?

**Comment by DBuit** [comment]
Hi guys,

still have this problem?

**Comment by MrHarcombe** [comment]
Unfortunately so, can't get my head into the CSS well enough to sort it myself 😕
![Screenshot_20200525-093115](https://user-images.githubusercontent.com/2182915/82794977-3cfb1a80-9e6b-11ea-911f-bc8ba8f92004.png)
![Screenshot_20200525-093110](https://user-images.githubusercontent.com/2182915/82795010-4b493680-9e6b-11ea-9a4b-8ae24ff0a728.png)

**Comment by gamer06** [comment]
For me I scroll down it’s appear. 
![072B31C9-04AA-4152-94DB-B45D81EBF52E](https://user-images.githubusercontent.com/23462360/82887795-6afe5e80-9f40-11ea-92e3-34e3ae3cf5bc.png)

**Comment by DBuit** [comment]
Strange and hard to fix because i do not have this problem.
I did change some stuff in my latest release, are you guys using the latest version of yesterday?

**Comment by gamer06** [comment]
I made the update now. And had a hard reboot, but still the same problem.

**Comment by MrHarcombe** [comment]
Likewise, sadly. Updated, refreshed, but still seeing the sidebar
underlaying the main panel on my mobile.

-- Ian

**Comment by MrHarcombe** [comment]
Updated to 0.1.7.5 and is now sorted for me. Many thanks 👍
