### ISSUE TITLE
Ability to hide topbar/hassmenu for non-admins?

### ISSUE THREAD

**Issue by dm7500** [DBuit/sidebar-card#60]
Loving the add-on, using it actively for my wall tablets. However, the ability to hide the topmenu and/or hassmenu for only certian users would be ideal, and would make configuring the dashboards using this add-on less cumbersome.

If it helps, [Kiosk mode](https://github.com/maykar/kiosk-mode) uses something like this to show/hide per user. I've tried this out, but it doesn't work with the sidebar add-on, which I'd prefer to use anyways.

**Comment by ry8s** [comment]
I love this idea!
