### ISSUE TITLE
Cannot edit dashboard due to removing top menu

### ISSUE THREAD

**Issue by ukmgranger** [DBuit/sidebar-card#61]
I have disabled the top menu and side menu, however there now seems to be no way to edit the dashboard.

**Comment by wtrbuit** [comment]
It is a bit hidden in the documentation but you can use this to get the sidebar and top menu back.

> When using hideTopMenu and/or hideHassSidebar you can disable this by adding **?sidebarOff** to the url. For example you get this url: https://myhomeassistant.duckdns.org/lovelace/home?sidebarOff

**Comment by ukmgranger** [comment]
Amazing - Many thanks!
