### ISSUE TITLE
navigating between lovelace dashboards

### ISSUE THREAD

**Issue by ChristopherLMiller** [DBuit/sidebar-card#64]
is this a thing thats possible or not?  i have like 5 lovelace dashboards and then utilize the top menu for different views in those still, but using the navigation element in the sidebar goes to the right page, but the sidebar doesn't appear till I reload the page

**Comment by artiscursive** [comment]
I just condensed all of mine into one dashboard.

**Comment by jwaz73** [comment]
I am having this same issue when using the `action: navigate` items in the sidebarMenu.  If I use the HA sidebar to change dashboards the sidebar loads with the dashboard.  If I use the sidebarMenu item to navigate to the dashboard the page loads but the sidebar does not load until I refresh the page.

I have cleared the browser cache and tried both Chrome and Firefox browsers with the same result.  I have the same sidebar config in each of the dashboards.  My dashboards have only one view in each dashboard but the sidebar is configured globally (at the root of the yaml, not in the `views:` section.
