### ISSUE TITLE
Home assistant 107

### ISSUE THREAD

**Issue by Tedsterh** [DBuit/sidebar-card#7]
Hi, I have been using this since this was released and I have had no problems, but after update home assistant to 107 it no longer shows up in my dashboards, I have made 2 dashboards and it uses the same file as I did in 106 but the sidebar does not show? Any ideas?

**Comment by DBuit** [comment]
Hi, you still have issues? i should work

**Comment by Tedsterh** [comment]
Hi, thank you, this is working perfectly now.
