### ISSUE TITLE
Gap Error

### ISSUE THREAD

**Issue by Tarusky80** [DBuit/sidebar-card#84]
Hi,

SITUATION:
<img width="675" alt="1" src="https://user-images.githubusercontent.com/95435097/230566977-b4e818ec-2820-4a05-89d8-a326322cc2c8.png">

AS IT SHOULD BE
<img width="284" alt="2" src="https://user-images.githubusercontent.com/95435097/230567062-b97b689b-50e0-419c-8a09-62321331b61e.png">

There is a gap which prevents me from seeing the chips in the first row of each column.
There is a solution? Thank you

**Comment by olaoups** [comment]
Hi!

It appears that it is the same issue as explained here:
https://github.com/DBuit/sidebar-card/issues/83#issuecomment-1500087192

**Comment by Tarusky80** [comment]
Oops, I missed the post

**Comment by almighty059** [comment]
Would that be the same thing that would fix this gap or do you think this is a separate issue?

![20230415_063236](https://user-images.githubusercontent.com/63380298/232217735-7fa356c7-e7bf-4d5b-85d9-8bf40910d91d.jpg)

**Comment by olaoups** [comment]
> @olaoups would that be the same fix for the gap that I'm getting in the below picture or do you think this is a separate issue?
> 
> ![20230415_063236](https://user-images.githubusercontent.com/63380298/232217735-7fa356c7-e7bf-4d5b-85d9-8bf40910d91d.jpg)

This is the same problem, yes! You can test my fix by downloading this JS file:

`https://github.com/olaoups/sidebar-card/tree/master/dist/sidebar-card.js`

And put into your installation.

Cheers

**Comment by DBuit** [comment]
i merged the fix that @olaoups made (thank you) it is in the new version.
