### ISSUE TITLE
Gap on the left since 2023.5

### ISSUE THREAD

**Issue by hesspoint** [DBuit/sidebar-card#86]
Since I updated to 2023.5 the sidebar does not go all the way to the left edge of the screen but leaves an empty space the exact size of the HA menu. Depending if the menu is expanded or compact the gap will be smaller or wider. I attached some pictures. It was working well just before the update in 2023.4.x

I have set
hidetopmenu: true
hideHassSidebar: true
showTopMenuOnMobile: true

Here is how it looks
![IMG_0035](https://user-images.githubusercontent.com/67288231/236630930-568efe35-9e4d-47dd-a6d0-3a34cb993595.jpeg)
![IMG_0036](https://user-images.githubusercontent.com/67288231/236630935-58508497-3f54-4169-b480-4579da556ac6.jpeg)

**Comment by akkaria** [comment]
I’ve got the same problem here since the latest update.

**Comment by hesspoint** [comment]
Is the update already released? Because in HACS I don't see an update yet. Or is it not yet in the stable release but in the beta? Thanks

**Comment by Mr-HaleYa** [comment]
I updated to 1.9.3 and mine still shows... cleared the cache, uninstalled then reinstalled, restarted HomeAssistant, and tried on different devices and browsers. still shows a gap on the left 
![image](https://user-images.githubusercontent.com/42821995/236962123-3eab889c-6128-4284-8ec1-a1854c44a361.png)
![image](https://user-images.githubusercontent.com/42821995/236962153-4f6d0bc2-89e6-40aa-9c19-2b4ad522d433.png)
The padding changes have not made a difference.
![image](https://user-images.githubusercontent.com/42821995/236962401-ba74c4c5-e62f-4237-9cfc-1027e1a55879.png)

**Comment by Mr-HaleYa** [comment]
Found that the hacstag value did not change? changed its value and everything was fixed. Does it usually change on updates? mine was `2418255740193` and I changed it to `2418255740194`
