### ISSUE TITLE
0.1.9.4 Top of sidebar cut off if menu not hidden

### ISSUE THREAD

**Issue by ccMatrix** [DBuit/sidebar-card#89]
![image](https://user-images.githubusercontent.com/96917/237026733-516b3bdc-edf9-4acb-8203-2ca75f5f8ded.png)

If I don't set hideTopMenu or hideHassSidebar or even if I set them to false this is the result. In previous 0.1.9.3 this didn't happen.
```
sidebar:
  [...]
  hideTopMenu: false
  hideHassSidebar: false
```

From what I found the new function `getHeaderHeightPx()` that uses marginTop always returns 0px on my install. When inpecting the DOM the element does indeed have no marginTop and the gap on top is generated using a paddingTop on the view container. 
![image](https://user-images.githubusercontent.com/96917/237033641-f2deb390-202a-452a-96ca-4d8a9eb252e3.png)

So if I change the code to `headerHeightPx = window.getComputedStyle(view).paddingTop;` it works.

Maybe the code can be changed to use the higher value of paddingTop and marginTop or the sum of the values to get the offset from the top.

Versions:
Home Assistant 2023.5.2
Frontend 20230503.3 - latest

Installed resources:
/local/atomic-calendar-revive.js?v=7.2.0
/local/kiosk-mode.js?v=1.9.0
/local/layout-card.js?v=2.4.4
/local/mini-media-player-bundle.js?v=1.16.5
/local/mushroom.js?v=2.7.1
/local/sidebar-card.js?v=0.1.9.4
/local/card-mod.js

**Comment by namorwoy** [comment]
the same

**Comment by andiukas** [comment]
The same

**Comment by mishoboss** [comment]
Any news on this one?

**Comment by chris173972** [comment]
Same issue here. 
![Screenshot 2023-08-08 163540](https://github.com/DBuit/sidebar-card/assets/5174337/a36dc425-3955-4e48-bf1d-5e4ae36169bd)

**Comment by andiukas** [comment]
clean browser cache

**Comment by KentuckyMC** [comment]
Same issue here, will be great if this will be added to this card. On maintenance of the page, I need to use the url with ?sidebarOff, and it also cuts the page like mentioned here. Fingers crossed it will be added.

**Comment by olaoups** [comment]
Hi @ccMatrix 

Could you try my patch ? Just use this repo: https://github.com/olaoups/sidebar-card and report me if it helps :-)

Thanks!

**Comment by ccMatrix** [comment]
This works for me. I did manually change marginTop to paddingTop in the dist file when I reported it and your patch seems to apply that same code now. The dist file from your repo and my modified one are now identical in that line. Would be great if you could merge that into the offical version!

**Comment by olaoups** [comment]
Thanks for the answer! I can't merge it by myself. I've made a merge request to @DBuit and he'll merge it if he accepts it (and if he has enough time) 😄
