### ISSUE TITLE
sidebar-card Analog Clock issue

### ISSUE THREAD

**Issue by syedkami** [DBuit/sidebar-card#9]
hi,
first i appreciate about this card style and look. which is quite impressive.
i am using Analog clock, there is issue in that when clock near to complete hour, then hour needle shows previous hour.
i am attaching picture. time is actually 3:55
 pm, but shows in clock like 2:55 pm. and after complete hour,its ok.
another asking, can i adjust size of analog clock.

thanks

![Analog_clock](https://user-images.githubusercontent.com/56224376/80703315-faf4e800-8afb-11ea-8471-ac8e44535b96.jpeg)
![analog_clock_02](https://user-images.githubusercontent.com/56224376/80703333-00523280-8afc-11ea-9a8d-98c69e142917.jpeg)

**Comment by MrHarcombe** [comment]
Off the top of the my head, I don't know how to adjust the size of the clock... but I have put in a pull request to fix for your other issue. You can fix it locally if you wish, until @DBuit chooses to accept or reject the change, if you are comfortable with code changes. It means having to dig into the compiled JS code in your running HomeAssistant instance?

**Comment by DBuit** [comment]
I merged @MrHarcombe fix
