### ISSUE TITLE
Sidebar covers Image

### ISSUE THREAD

**Issue by MarshallGitHub97** [DBuit/sidebar-card#97]
Hi,
I use a Floorplan in combination with sidebar and once the light image of a room is active it is cut by a kin of shadow of the sidebar.

When i deactivate the sidebar all is fine.

![image](https://github.com/DBuit/sidebar-card/assets/139146972/afeb95a4-cf64-4bb1-9ca0-dbdee657756f)

**Comment by ayouss007** [comment]
i have the same issue did you fix it?

**Comment by m0uh85** [comment]
Same here. I have the same issue? What was the reason?

**Comment by MarshallGitHub97** [comment]
> Same here. I have the same issue? What was the reason?

I can´t remember excactly, but must be with the style of the pictures.
Can You send me you code? The issue is with ?

**Comment by m0uh85** [comment]
> > Same here. I have the same issue? What was the reason?
> 
> I can´t remember excactly, but must be with the style of the pictures. Can You send me you code? The issue is with ?

Do you need only the code for the floorplan? the side bar? or my whole RAW config?
