### ISSUE TITLE
Clock under top menu

### ISSUE THREAD

**Issue by tiwek** [DBuit/sidebar-card#99]
Hi. 

Do you have an idea how to fix the clock not hiding under the top menu?

![image](https://github.com/DBuit/sidebar-card/assets/74269691/01e64a76-0cce-460a-9b2e-27c736578e16)

**Comment by magicmellon** [comment]
Having same issue - I assume something has updated in the backend of HA that has broken this a little?

**Comment by MichelJourdain** [comment]
In the clock style settings, you can add the following parameter and adapt it according to your needs.

padding-top: 70px

```
     .digitalClock {0
        color: rgba(255, 255, 255, 0.7)!important;
        font-size: 5.41vw!important;
        font-weight: 500!important;
        letter-spacing: -0.05vw!important;
        text-align: center;
        padding-top: 70px
     }

```

**Comment by olaoups** [comment]
Hi @tiwek 

Could you try my patch ? Just use this repo: https://github.com/olaoups/sidebar-card and report me if it helps :-)

Thanks!

**Comment by tiwek** [comment]
> Hi @tiwek
> 
> Could you try my patch ? Just use this repo: https://github.com/olaoups/sidebar-card and report me if it helps :-)
> 

Works nice.  Tanks.

![image](https://github.com/DBuit/sidebar-card/assets/74269691/16f26104-d6a5-4c77-b6b3-0ac4a1ed0baf)

**Comment by DBuit** [comment]
@olaoups fix is merged so should be good now
